-- MariaDB/MySQL 최신 버전에서 에러 나는 패턴입니다.
-- '0000-00-00 00:00:00'은 더 이상 유효한 TIMESTAMP 기본값이 아니기 때문
-- TIMESTAMP NULL DEFAULT NULL, 기본값 사용
-- MySQL Script generated by MySQL Workbench
-- Fri May 16 11:06:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hizib
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hizib` ;

-- -----------------------------------------------------
-- Schema hizib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hizib` DEFAULT CHARACTER SET utf8mb4 ;
USE `hizib` ;

DROP TABLE IF EXISTS `hizib`.`admin` ;

CREATE TABLE IF NOT EXISTS `hizib`.`admin` (
  `admin_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(255) NOT NULL DEFAULT '',
  `passwd` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `handphone` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `loginTimes` INT(10) NULL DEFAULT 0,
  `lastLogin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`admin_id`),
  INDEX `id` (`id` ASC) VISIBLE,
  INDEX `passwd` (`passwd` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `handphone` (`handphone` ASC) VISIBLE,
  INDEX `email` (`email` ASC) VISIBLE,
  INDEX `lastLogin` (`lastLogin` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`code` ;

CREATE TABLE IF NOT EXISTS `hizib`.`code` (
  `code_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gcode` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `nickname` VARCHAR(255) NOT NULL DEFAULT '',
  `sortNum` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `isUse` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`code_id`),
  INDEX `gcode` (`gcode` ASC) VISIBLE,
  INDEX `code` (`code` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `nickname` (`nickname` ASC) VISIBLE,
  INDEX `sortNum` (`sortNum` ASC) VISIBLE,
  INDEX `isUse` (`isUse` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`faceplusplus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`faceplusplus` ;


CREATE TABLE IF NOT EXISTS `hizib`.`faceplusplus` (
  `faceplusplus_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL DEFAULT '',
  `host` VARCHAR(255) NOT NULL DEFAULT '',
  `page` VARCHAR(255) NOT NULL DEFAULT '',
  `header` LONGTEXT NULL DEFAULT NULL,
  `body` LONGTEXT NULL DEFAULT NULL,
  `response` LONGTEXT NULL DEFAULT NULL,
  `status` INT(3) NOT NULL DEFAULT 200,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`faceplusplus_id`),
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `host` (`host` ASC) VISIBLE,
  INDEX `page` (`page` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 19369
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`faq` ;


CREATE TABLE IF NOT EXISTS `hizib`.`faq` (
  `faq_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL DEFAULT '',
  `answer` TEXT NULL DEFAULT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`faq_id`),
  INDEX `question` (`question` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`user` ;


CREATE TABLE IF NOT EXISTS `hizib`.`user` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(255) NOT NULL DEFAULT '',
  `passwd` VARCHAR(255) NOT NULL DEFAULT '',
  `fcm_token` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `nickname` VARCHAR(255) NOT NULL DEFAULT '',
  `authcode` VARCHAR(255) NOT NULL DEFAULT '',
  `ci` VARCHAR(255) NOT NULL DEFAULT '',
  `handphone` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(255) NOT NULL DEFAULT '',
  `picture` LONGTEXT NULL DEFAULT NULL,
  `faces` LONGTEXT NULL DEFAULT NULL,
  `loginTimes` INT(10) NULL DEFAULT 0,
  `lastLogin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `isUse` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  INDEX `id` (`id` ASC) VISIBLE,
  INDEX `passwd` (`passwd` ASC) VISIBLE,
  INDEX `fcm_token` (`fcm_token` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `nickname` (`nickname` ASC) VISIBLE,
  INDEX `ci` (`ci` ASC) VISIBLE,
  INDEX `handphone` (`handphone` ASC) VISIBLE,
  INDEX `email` (`email` ASC) VISIBLE,
  INDEX `lastLogin` (`lastLogin` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  INDEX `isUse` (`isUse` ASC) VISIBLE,
  INDEX `authcode` (`authcode` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8mb4;



-- -----------------------------------------------------
-- Table `hizib`.`fcm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`fcm` ;

CREATE TABLE IF NOT EXISTS `hizib`.`fcm` (
  `fcm_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `body` TEXT NULL DEFAULT NULL,
  `data` LONGTEXT NULL DEFAULT NULL,
  `options` LONGTEXT NULL DEFAULT NULL,
  `result` VARCHAR(255) NOT NULL DEFAULT '',
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `readDate` TIMESTAMP NULL DEFAULT NULL,
  `status` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`fcm_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `title` (`title` ASC) VISIBLE,
  INDEX `result` (`result` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  INDEX `readDate` (`readDate` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE,
  CONSTRAINT `fcm_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 793
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`logger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`logger` ;

CREATE TABLE IF NOT EXISTS `hizib`.`logger` (
  `logger_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` INT(1) NOT NULL DEFAULT 1,
  `location` VARCHAR(255) NOT NULL DEFAULT '',
  `data` LONGTEXT NULL DEFAULT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`logger_id`),
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `location` (`location` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6864
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`ncloud_sms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`ncloud_sms` ;


CREATE TABLE IF NOT EXISTS `hizib`.`ncloud_sms` (
  `ncloud_sms_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `host` VARCHAR(255) NOT NULL DEFAULT '',
  `page` VARCHAR(255) NOT NULL DEFAULT '',
  `requestId` VARCHAR(255) NOT NULL DEFAULT '',
  `type` INT(1) NOT NULL DEFAULT 1,
  `contentType` VARCHAR(255) NOT NULL DEFAULT 'COMM',
  `countryCode` VARCHAR(255) NOT NULL DEFAULT '82',
  `callback` VARCHAR(255) NOT NULL DEFAULT '',
  `subject` VARCHAR(255) NOT NULL DEFAULT '',
  `content` VARCHAR(255) NOT NULL DEFAULT '',
  `messages` LONGTEXT NULL DEFAULT NULL,
  `files` LONGTEXT NULL DEFAULT NULL,
  `data` LONGTEXT NULL DEFAULT NULL,
  `resultCode` INT(3) NOT NULL DEFAULT 202,
  `result` LONGTEXT NULL DEFAULT NULL,
  `rsvTimezone` VARCHAR(255) NOT NULL DEFAULT 'Asia/Seoul',
  `rsvDate` TIMESTAMP NULL DEFAULT NULL,
  `requestDate` TIMESTAMP NULL DEFAULT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`ncloud_sms_id`),
  INDEX `host` (`host` ASC) VISIBLE,
  INDEX `page` (`page` ASC) VISIBLE,
  INDEX `requestId` (`requestId` ASC) VISIBLE,
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `contentType` (`contentType` ASC) VISIBLE,
  INDEX `countryCode` (`countryCode` ASC) VISIBLE,
  INDEX `callback` (`callback` ASC) VISIBLE,
  INDEX `subject` (`subject` ASC) VISIBLE,
  INDEX `content` (`content` ASC) VISIBLE,
  INDEX `resultCode` (`resultCode` ASC) VISIBLE,
  INDEX `rsvTimezone` (`rsvTimezone` ASC) VISIBLE,
  INDEX `rsvDate` (`rsvDate` ASC) VISIBLE,
  INDEX `requestDate` (`requestDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 171
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`qna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`qna` ;

CREATE TABLE IF NOT EXISTS `hizib`.`qna` (
  `qna_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `comment` TEXT NULL DEFAULT NULL,
  `reply` TEXT NULL DEFAULT NULL,
  `replyDate` TIMESTAMP NULL DEFAULT NULL,
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`qna_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `title` (`title` ASC) VISIBLE,
  INDEX `replyDate` (`replyDate` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE,
  CONSTRAINT `qna_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_group` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_group` (
  `smartdoor_group_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `areacode` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `address` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`smartdoor_group_id`),
  INDEX `areacode` (`areacode` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor` (
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_group_id` BIGINT(20) UNSIGNED NOT NULL,
  `code` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `dong` VARCHAR(255) NOT NULL DEFAULT '',
  `ho` VARCHAR(255) NOT NULL DEFAULT '',
  `ble` VARCHAR(255) NOT NULL DEFAULT '',
  `isDoorOpen` INT(1) NOT NULL DEFAULT 0,
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`smartdoor_id`),
  INDEX `smartdoor_group_id` (`smartdoor_group_id` ASC) VISIBLE,
  INDEX `code` (`code` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `dong` (`dong` ASC) VISIBLE,
  INDEX `ho` (`ho` ASC) VISIBLE,
  INDEX `ble` (`ble` ASC) VISIBLE,
  INDEX `isDoorOpen` (`isDoorOpen` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE,
  CONSTRAINT `smartdoor_ibfk_1`
    FOREIGN KEY (`smartdoor_group_id`)
    REFERENCES `hizib`.`smartdoor_group` (`smartdoor_group_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_guestkey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_guestkey` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_guestkey` (
  `smartdoor_guestkey_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `handphone` VARCHAR(255) NOT NULL DEFAULT '',
  `passwd` VARCHAR(255) NOT NULL DEFAULT '',
  `startDate` TIMESTAMP NULL DEFAULT NULL,
  `stopDate` TIMESTAMP NULL DEFAULT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`smartdoor_guestkey_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `handphone` (`handphone` ASC) VISIBLE,
  INDEX `passwd` (`passwd` ASC) VISIBLE,
  INDEX `startDate` (`startDate` ASC) VISIBLE,
  INDEX `stopDate` (`stopDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  INDEX `status` (`status` ASC) VISIBLE,
  CONSTRAINT `smartdoor_guestkey_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE,
  CONSTRAINT `smartdoor_guestkey_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_item` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_item` (
  `smartdoor_item_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_item_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_item_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 276
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_log` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_log` (
  `smartdoor_log_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `type` INT(2) NOT NULL DEFAULT 0,
  `code` VARCHAR(255) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_log_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `code` (`code` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_log_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4777
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_message` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_message` (
  `smartdoor_message_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `to_user_id` BIGINT(20) UNSIGNED NOT NULL,
  `from_user_id` BIGINT(20) UNSIGNED NOT NULL,
  `msg` VARCHAR(255) NOT NULL DEFAULT '',
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_message_id`),
  INDEX `to_user_id` (`to_user_id` ASC) VISIBLE,
  INDEX `from_user_id` (`from_user_id` ASC) VISIBLE,
  INDEX `msg` (`msg` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_message_ibfk_1`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `smartdoor_message_ibfk_2`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_notice` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_notice` (
  `smartdoor_notice_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_notice_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `title` (`title` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_notice_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 130
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_schedule` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_schedule` (
  `smartdoor_schedule_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `dday` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_schedule_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `dday` (`dday` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_schedule_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 137
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_user` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_user` (
  `smartdoor_user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `isOwner` INT(1) NOT NULL DEFAULT 1,
  `isDoorbell` INT(1) NOT NULL DEFAULT 1,
  `isAccessRecord` INT(1) NOT NULL DEFAULT 1,
  `isMotionDetect` INT(1) NOT NULL DEFAULT 1,
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `isUse` INT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`smartdoor_user_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `isOwner` (`isOwner` ASC) VISIBLE,
  INDEX `isDoorbell` (`isDoorbell` ASC) VISIBLE,
  INDEX `isAccessRecord` (`isAccessRecord` ASC) VISIBLE,
  INDEX `isMotionDetect` (`isMotionDetect` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  INDEX `isUse` (`isUse` ASC) VISIBLE,
  CONSTRAINT `smartdoor_user_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE,
  CONSTRAINT `smartdoor_user_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 116
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_user_invite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_user_invite` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_user_invite` (
  `smartdoor_user_invite_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `handphone` VARCHAR(255) NOT NULL DEFAULT '',
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_user_invite_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE,
  INDEX `handphone` (`handphone` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_user_invite_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE,
  CONSTRAINT `smartdoor_user_invite_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `hizib`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`smartdoor_vod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`smartdoor_vod` ;

CREATE TABLE IF NOT EXISTS `hizib`.`smartdoor_vod` (
  `smartdoor_vod_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `smartdoor_id` BIGINT(20) UNSIGNED NOT NULL,
  `gcode` VARCHAR(255) NOT NULL DEFAULT '',
  `code` VARCHAR(255) NOT NULL DEFAULT '',
  `filepath` VARCHAR(255) NOT NULL DEFAULT '',
  `fileurl` VARCHAR(255) NOT NULL DEFAULT '',
  `filename` VARCHAR(255) NOT NULL DEFAULT '',
  `comment` TEXT NULL DEFAULT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`smartdoor_vod_id`),
  INDEX `smartdoor_id` (`smartdoor_id` ASC) VISIBLE,
  INDEX `gcode` (`gcode` ASC) VISIBLE,
  INDEX `code` (`code` ASC) VISIBLE,
  INDEX `filepath` (`filepath` ASC) VISIBLE,
  INDEX `fileurl` (`fileurl` ASC) VISIBLE,
  INDEX `filename` (`filename` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE,
  CONSTRAINT `smartdoor_vod_ibfk_1`
    FOREIGN KEY (`smartdoor_id`)
    REFERENCES `hizib`.`smartdoor` (`smartdoor_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5707
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`ums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`ums` ;

CREATE TABLE IF NOT EXISTS `hizib`.`ums` (
  `ums_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL DEFAULT '',
  `type` INT(2) NOT NULL DEFAULT 1,
  `subject` VARCHAR(255) NOT NULL DEFAULT '',
  `callback` VARCHAR(255) NOT NULL DEFAULT '',
  `callbackUrl` VARCHAR(255) NOT NULL DEFAULT '',
  `toPerson` LONGTEXT NULL DEFAULT NULL,
  `msg` TEXT NULL DEFAULT NULL,
  `data` LONGTEXT NULL DEFAULT NULL,
  `requestUrl` VARCHAR(255) NOT NULL DEFAULT '',
  `ip` VARCHAR(255) NOT NULL DEFAULT '',
  `totalCount` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `succCount` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `failCount` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `isRsv` INT(1) NOT NULL DEFAULT 0,
  `sendDate` TIMESTAMP NULL DEFAULT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`ums_id`),
  INDEX `code` (`code` ASC) VISIBLE,
  INDEX `type` (`type` ASC) VISIBLE,
  INDEX `subject` (`subject` ASC) VISIBLE,
  INDEX `callback` (`callback` ASC) VISIBLE,
  INDEX `callbackUrl` (`callbackUrl` ASC) VISIBLE,
  INDEX `requestUrl` (`requestUrl` ASC) VISIBLE,
  INDEX `ip` (`ip` ASC) VISIBLE,
  INDEX `totalCount` (`totalCount` ASC) VISIBLE,
  INDEX `succCount` (`succCount` ASC) VISIBLE,
  INDEX `failCount` (`failCount` ASC) VISIBLE,
  INDEX `isRsv` (`isRsv` ASC) VISIBLE,
  INDEX `sendDate` (`sendDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 252
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hizib`.`weather`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hizib`.`weather` ;

CREATE TABLE IF NOT EXISTS `hizib`.`weather` (
  `weather_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `areacode` VARCHAR(255) NOT NULL DEFAULT '',
  `timecode` VARCHAR(255) NOT NULL DEFAULT '',
  `location` VARCHAR(255) NOT NULL DEFAULT '',
  `currentTemperature` FLOAT NOT NULL DEFAULT 0,
  `minTemperature` FLOAT NOT NULL DEFAULT 0,
  `maxTemperature` FLOAT NOT NULL DEFAULT 0,
  `sky` VARCHAR(255) NOT NULL DEFAULT '',
  `icon` INT(2) NOT NULL DEFAULT 0,
  `finedust` VARCHAR(255) NOT NULL DEFAULT '',
  `ultrafinedust` VARCHAR(255) NOT NULL DEFAULT '',
  `lists` LONGTEXT NULL DEFAULT NULL,
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`weather_id`),
  INDEX `areacode` (`areacode` ASC) VISIBLE,
  INDEX `timecode` (`timecode` ASC) VISIBLE,
  INDEX `location` (`location` ASC) VISIBLE,
  INDEX `currentTemperature` (`currentTemperature` ASC) VISIBLE,
  INDEX `minTemperature` (`minTemperature` ASC) VISIBLE,
  INDEX `maxTemperature` (`maxTemperature` ASC) VISIBLE,
  INDEX `sky` (`sky` ASC) VISIBLE,
  INDEX `icon` (`icon` ASC) VISIBLE,
  INDEX `finedust` (`finedust` ASC) VISIBLE,
  INDEX `ultrafinedust` (`ultrafinedust` ASC) VISIBLE,
  INDEX `updateDate` (`updateDate` ASC) VISIBLE,
  INDEX `regDate` (`regDate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

