# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# HTTP 및 CORS 설정
http:
  cors_allowed_origins:
    - https://example.com
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
